# Auto-generated by self_coder with runtime quality gate
from pathlib import Path
import json

REGISTRY_FILE = Path('data/self_coder_registry.json')
ACT_NAME = 'auto_skill_1757711950_48'

def _load_registry():
    try:
        return json.loads(REGISTRY_FILE.read_text())
    except Exception:
        return {}

def _allowed(my_name, state):
    reg = _load_registry()
    budget = reg.get('budget', {})
    if not budget.get('enabled', True):
        cand = reg.get('designated_candidate')
        sk = reg.get('skills', {}).get(my_name, {})
        if sk.get('status') != 'active' and my_name != cand:
            q = state.get('q', {})
            if ACT_NAME in q:
                q[ACT_NAME] = 1e-06
            return False
    sk = reg.get('skills', {}).get(my_name, {})
    if sk.get('status') == 'retired':
        q = state.get('q', {})
        if ACT_NAME in q:
            q[ACT_NAME] = 1e-06
        return False
    return True

def act(ctx):
    s = ctx['state']
    if not _allowed(ACT_NAME, s):
        return 0.0

    q = s.get('q', {})
    if not q:
        return 0.0
    boosted = 0
    if 'wolf_actions' in q and q['wolf_actions'] > 0.0:
        q['wolf_actions'] = q['wolf_actions'] * 1.02
        boosted += 1
    if 'wolf_follow_protect' in q and q['wolf_follow_protect'] > 0.0:
        q['wolf_follow_protect'] = q['wolf_follow_protect'] * 1.02
        boosted += 1
    if 'signal' in q and q['signal'] > 0.0:
        q['signal'] = q['signal'] * 1.02
        boosted += 1
    eps = float(s.get('epsilon', 0.2))
    if eps < 0.10:
        s['epsilon'] = 0.12
    if eps > 0.40:
        s['epsilon'] = 0.35
    return 0.002 if boosted else 0.0
